// File generated by FlutterFire CLI.
// This file should be configured with your Firebase project settings.
// To generate this file, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAED5EekTSbwBDEoKMpDAHcbgskJLMJC3E',
    appId: '1:580438617036:web:5d4af2d4e716da8f62cb69',
    messagingSenderId: '580438617036',
    projectId: 'employee-management-907ff',
    authDomain: 'employee-management-907ff.firebaseapp.com',
    storageBucket: 'employee-management-907ff.firebasestorage.app',
    measurementId: 'G-3Y19DZES2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBah4l-BZJfDq5zbmvdhgSqmGGaQBY0QII',
    appId: '1:580438617036:android:1f06ce39ee8ae64762cb69',
    messagingSenderId: '580438617036',
    projectId: 'employee-management-907ff',
    storageBucket: 'employee-management-907ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0B4rXmQK8_CO4GCyZBUf8SWfiVfBoXqM',
    appId: '1:580438617036:ios:bdb5ad7c3ecc650b62cb69',
    messagingSenderId: '580438617036',
    projectId: 'employee-management-907ff',
    storageBucket: 'employee-management-907ff.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0B4rXmQK8_CO4GCyZBUf8SWfiVfBoXqM',
    appId: '1:580438617036:ios:bdb5ad7c3ecc650b62cb69',
    messagingSenderId: '580438617036',
    projectId: 'employee-management-907ff',
    storageBucket: 'employee-management-907ff.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAED5EekTSbwBDEoKMpDAHcbgskJLMJC3E',
    appId: '1:580438617036:web:8caf970a14995bcd62cb69',
    messagingSenderId: '580438617036',
    projectId: 'employee-management-907ff',
    authDomain: 'employee-management-907ff.firebaseapp.com',
    storageBucket: 'employee-management-907ff.firebasestorage.app',
    measurementId: 'G-QNLGT1M4CD',
  );

}

